### ISSUE TITLE
GitHub page doesn't surve images whose filenames start with a underscore `_`

### ISSUE THREAD

**Issue by xiaohk** [KiwiKilian/eleventy-plugin-og-image#228]
Sometimes the generated image's hash names can start with `_`. However, GitHub page doesn't serve these files :(

**Comment by xiaohk** [comment]
A solution is to include `.nojekyll` in the directory of the GitHub page.

**Comment by KiwiKilian** [comment]
Thank you for raising the issue and posting [the workaround](https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/). From 2.1.3 onwards it should not be necessary anymore. I've changed the hex digest just like vite does it: https://github.com/vitejs/vite/blob/6a07243a0ecc06a81e87d5b3de7b88023a045e6b/packages/vite/src/node/utils.ts#L1030
