### ISSUE TITLE
New context (`this`) way for working with plugin

### ISSUE THREAD

**Issue by what1s1ove** [KiwiKilian/eleventy-plugin-og-image#252]
Hi! Thanks for such an awesome plugin!

I wanted to ask why the new beta version uses the context (`this`) style for working with the plugin? For example:

```js
config.addPlugin(ogImage, {
  outputFileSlug: function () {
    return this.data.page.fileSlug;
  },
});
```

While the current version uses the approach of passing context through function parameters:

```js
config.addPlugin(ogImage, {
  getOutputFileSlug: ({ context }) => context.page.fileSlug,
});
```

In my opinion, the approach using parameters is better. Here are my main points:

1. It is simpler to understand and maintain.
2. It is easier to type (using `jsdoc` or similar).
3. It generally fits better with the style of native 11ty plugins (for example, the image plugin and the `filenameFormat` function).
  ```js
  	config.addPlugin(Image.eleventyImageTransformPlugin, {
		filenameFormat: (_id, source, width, format) => {
			let extension = extname(source)
			let name = basename(source, extension)

			return `${name}-${width}w.${format}`
		}
	})
  ```

These are the points that come to mind, but it would be great to hear what you think about this.

**Comment by KiwiKilian** [comment]
I share your concerns. I'm thinking about just passing the class instance as parameter. Hope to have some time soon to optimize.

**Comment by KiwiKilian** [comment]
Change with the new beta, give it a try!
