### ISSUE TITLE
LinkedIn expects `name="image"` within the `<meta/>` tag 

### ISSUE THREAD

**Issue by ddamato** [KiwiKilian/eleventy-plugin-og-image#33]
When you send a URL into the post inspector, the result expects the following construction.

`<meta name="image" property="og:image" content="[Image URL here]">`

Looks like this would be a quick change [at this line](https://github.com/KiwiKilian/eleventy-plugin-og-image/blob/main/.eleventy.js#L39).

**Comment by KiwiKilian** [comment]
Thanks for your input! Does it detect the og image of your example in the [post inspector](https://www.linkedin.com/post-inspector/)? I think it's just an example, how they try to find the og image. It works successfully for me with the current output (without `name="image"`, or did I miss another difference?). They also [document it](https://www.linkedin.com/help/linkedin/answer/a521928/make-your-website-shareable-on-linkedin?lang=en) like without `name`.

**Comment by ddamato** [comment]
> Does it detect the og image of your example in the [post inspector](https://www.linkedin.com/post-inspector/)?

No it uses the one for the homepage instead. [Try with my latest post](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fblog.damato.design%2Fposts%2Fterminal-career%2F).

The og-image should have the title of the specific article rendered in the image, but it's using the homepage og-image instead. However, it's entirely possible it's just LinkedIn scraping my metadata incorrectly. I have the same problem with the title and description even after adding the `name` attributes as they've recommended.

**Comment by ddamato** [comment]
Ok yeah, issue is on my end. It wasn't rendering the correct absolute url. However, I'd appreciate your suggestion since the twitter metatags are different but I'd like to send the same image there also. Rendering the `outputUrl` in my template would be better than rendering the entire HTML, in my opinion.

**Comment by KiwiKilian** [comment]
@ddamato I've adde the [`generateHTML` option](https://github.com/KiwiKilian/eleventy-plugin-og-image#configuration). You could just modify the markup generated by the shortcode. If you really just want to get the output path and generate the markup in youre page templates you can use the [capture approach](https://github.com/KiwiKilian/eleventy-plugin-og-image#capture-output-url). Or as most customizable variant, create a [custom shortcode](https://github.com/KiwiKilian/eleventy-plugin-og-image#custom-shortcode).
